### ISSUE TITLE
Putting the app into the background

### ISSUE THREAD

**Issue by wardellchandler** [konmik/nucleus#95] opened 2016-05-15 00:06 UTC
With the current examples (and the current NucleusFragment/Activities you have provided), if you have a request running and put the app into the background, the Presenter will still call the callbacks you have set.

The simple fix is to just call onDropView in onPause instead of in onDestroyView/onDestroy for Fragments and Activities, but this might have some ramifications that I'm not aware of.

**Comment by konmik** [comment] 2016-05-15 10:55
Isn't it a duplicate of https://github.com/konmik/nucleus/issues/90 ?

**Comment by wardellchandler** [comment] 2016-05-15 14:03
Whoops, sorry, it is.

**Closed** 2016-05-15 14:47 UTC
